project:
  type: book
  output-dir: docs
  
book:
  title: "Türkiye Kuşlarının Doğa Tarihi"
  author:
    name: "Kerem Ali Boyla, Editör"
    orcid: "0000-0002-1825-0097"
  date: "2025-05-19"
  date-format: "MMMM YYYY"
  subtitle: "Türlerin Coğrafi Yayılışı, Üreme Biyolojisi ve Taksonomik Durumu"
  cover-image: kapak3.png
  favicon: kapak3.png
  repo-url: https://github.com/keremaliboyla/turkiye-kuslari
  repo-actions: [edit, issue]
  # sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - 00_giris.qmd
    - 01_ordekgiller.qmd
    - 02_tavukgiller_vd.qmd
    - 03_bataklik-kuslari.qmd
    - 04_cilibitlar.qmd
    - 05_cullukgiller.qmd
    - 06_martilar.qmd
    - 07_deniz-ve-gol-kuslari.qmd
    - 08_yirticilar.qmd
    - 09_baykuslar.qmd
    - 10_otucu-oncesi.qmd
    - 11_kargamsilar.qmd
    - 12_toygarlar.qmd
    - 13_kamiscinlar.qmd
    - 14_otlegenler.qmd
    - 15_tirmasiklar.qmd
    - 16_sinekkapanlar.qmd
    - 17_serceler.qmd
    - 18_ispinozlar.qmd
    - references.qmd

bibliography: references.bib
csl: nature.csl
number-sections: false

format:
  html:
    grid:
      body-width: 680px
      sidebar-width: 220px
      margin-width: 220px
      gutter-width: 1.5rem
    theme: cosmo
    number-depth: 1
    title-block-style: none
  # pdf:
  #   pdf-engine: lualatex
  #   documentclass: scrreprt
  #   classoption: twocolumn
  #   papersize: a4
  #   toc-title: "İçindekiler"
  #   number-depth: 0
  #   mainfont: "TeX Gyre Pagella"
  #   sansfont: "Arial"
  #   include-in-header: header.tex
  #   geometry:
  #     - inner=2cm
  #     - outer=2cm
  #     - top=2cm
  #     - bottom=2cm
  #     - headsep=22pt
  #     - headheight=11pt
  #     - footskip=33pt
  #     - ignorehead
  #     - ignorefoot
  #     - heightrounded
    # epub: default

editor: visual