project:
  type: book
  output-dir: docs

book:
  title: "Türkiye Kuşlarının Doğa Tarihi"
  cover-image: kapak3.png
  favicon: kapak3.png
  # repo-url: https://github.com/keremaliboyla/turkiye-kuslari
  # repo-actions: [edit, issue]
  # sharing: [twitter, facebook]
  
  chapters:
    - index.qmd
    - 01_ordekgiller.qmd
    - 02_tavukgiller_vd.qmd
    - 03_bataklik-kuslari.qmd
    - 04_cilibitlar.qmd
    - 05_cullukgiller.qmd
    - 06_martilar.qmd
    - 07_deniz-ve-gol-kuslari.qmd
    - 08_yirticilar.qmd
    - 09_baykuslar.qmd
    - 10_otucu-oncesi.qmd
    - 11_kargamsilar.qmd   # 31 Mart
    # - 12_toygarlar.qmd     # 14 Nisan
    # - 13_civginlar.qmd     # 14 Nisan
    # - 14_otlegenler.qmd    # 28 Nisan
    # - 15_tirmasiklar.qmd   # 28 Nisan
    # - 16_sinekkapanlar.qmd # 12 Mayıs
    # - 17_serceler.qmd      # 12 Mayıs
    # - 18_ispinozlar.qmd    # 19 Mayıs
    - part: "Ekler"
      chapters:
        - 00_tarihce_ve_tesekkur.qmd
        - 00_turkiye_ornitoloji_tarihi.qmd
        - 00_bilgi_bosluklari.qmd
    - references.qmd

bibliography: references.bib
csl: journal-of-zoology.csl

format:
  html:
    grid:
      sidebar-width: 200px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: cosmo
    number-depth: 1
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
    
editor: visual