project:
  type: book
  output-dir: docs

book:
  # repo-url: https://github.com/keremaliboyla/turkiye-kuslari
  # repo-actions: [edit, issue]
  title: "Türkiye Kuşları"
  author: "Kerem Ali Boyla, Guy Kirwan, Barbaros Demirci, Hilary Welch, Metehan Özen, Peter Castell, Tim Marlow"
  date: "2024-10-04"
  chapters:
    - index.qmd
    - 01_ordekgiller.qmd
    - 02_tavukgiller.qmd
    - 03_deniz-ve-gol-kuslari.qmd
    # - 04_yirticilar.qmd
    # - 05_bataklik-kuslari.qmd
    # - 06_cilibitlar.qmd
    # - 07_cullukgiller.qmd
    # - 08_martilar.qmd
    # - 09_karakuslari.qmd
    # - 10_otucu-oncesi.qmd
    # - 11_kargamsilar.qmd
    # - 12_toygarlar.qmd
    # - 13_civginlar.qmd
    # - 14_otlegenler.qmd
    # - 15_tirmasiklar.qmd
    # - 16_sinekkapanlar.qmd
    # - 17_serceler.qmd
    # - 18_ispinozlar.qmd
    # - ekler.qmd
    - references.qmd

bibliography: references.bib
csl: acta-ornithologica.csl

format:
  html:
    grid:
      sidebar-width: 180px
      margin-width: 180px
      # gutter-width: 1.5rem
    theme: cosmo 
    number-depth: 1
  # pdf:
  #   documentclass: scrreprt
  # epub:
  #   toc: true
  #   lang: tr-TR

editor: visual