---
title: "Ekler"
---

## Bilgi Dağarcığımız

Geoff Welch, Hilary Welch and Sancar Barış

Geçtiğimiz son 15-20 yılda, Türkiye'nin kuşları hakkındaki bilgimiz büyük ölçüde, yerli bir kuş gözlemcisi ve doğa koruma topluluğunun yetişmesine bağlı olarak, önemli gelişme göstermiştir. Bu bölüm Türkiye'nin kuşları hakkındaki bilgimizi kısıtlayan, bazıları genel, diğerleri ise oldukça çok özel temel sorunları tanımlamanın yanı sıra, geleceğe bakarak Türk kuş faunasına dair bundan sonra yapılabilecek önemli hedefleri ortaya koyar.

Türlerin dağılımları

Kuşların dağılımı mı, yoksa kuş gözlemcilerinin mi? Yakın zamanlara dek, Türkiye kuş veri havuzu büyük ölçüde tatil için Batı Avrupa'dan gelen kuş gözlemcilerinin katkısıyla oluşuyordu. Ülkeyi ziyaret eden yabancı kuş gözlemcileri kısa tatilleri boyunca mümkün olduğu kadar çok yeni tür ve farklı yaşam ortamı görmek isterler; Tüm bunlar önemli ölçüde taraflı veri oluşturur; kuş gözlemcileri hep aynı yere, yılın hep aynı zamanında giderler ve hep aynı kuşları gözlemlerler.

Türk kuş gözlemcilerinin tercih ettikleri gözlem yerleri daha çok yaşadıkları yerlerle ilişkilidir. Farklı yöntemler bulunması gerektiğini ortaya koyar.

Standart veri - türler var ya da yok

1998 ile 2003 arasında, standart yöntemler kullanarak Türkiye'nin geniş alanlarında, üreyen kuşlar hakkında veri toplayan üç önemli proje - Konya Havzası'nda (Eken & Magnin 1999), Akdeniz ormanlarında (Zeydanlı vd. 2005) ve Güney Doğu Anadolu'da (Welch 2004)- yürütülmüştür. Böylece, ilk defa, araştırma yerleri nadir türlerin varlığı ya da kuşların yoğunlaştığı alanların bulunması gibi daha önceki bilgilerden etkilenmeden tarafsız saptanmış oldu ve elde edilen veri bize kuşların kesinlikte nerelerde bulunduklarını ama aynı zamanda neredeyse kesinlikle nerede olmadıklarını da söyleyebildi. Önemli ölçüde daha fazla insan gücü gerektiren, organize etmesi güç ve nispeten pahalı bu tür çalışmalara

Yaygın" türlerin dağılımı tüm kuş gözlemcilerinin bilinç dışı oluşturdukları, her yerde bulundukları varsayımı ile -kargaları, toygarları, serçeleri, sığırcıkları, evcil güvercinleri- yeterince kaydetmemekten suçludurlar. Nitekim kumru, hareket halindeki bir araçtan kolayca değerlendirilebilecek bir kuştur. Kuş kitaplarında tüm Türkiye'de bulunduğu düşünülür. 2005'de ülkenin kuzey batısında iki hafta boyunca tam da yapılan saha çalışmasında Erzurum kuzeyinde "olmadığı", Kars'ta hiç bulunmadığı ve yeniden ancak Karadeniz'de Yeşilırmak ovasında ortaya çıktığı belirlendi.

Nadir türlerin dağılımındaki değişiklikler

\(2\) Statü

Kızıl sırtlı örümcekkuşu bu duruma iyi bir örnek oluşturur, bu tür göç sırasında son derece yaygındır ve kuş kitapları ve arazi rehberlerinin çoğunda Türkiye'nin büyük kısmında ürüyor olarak gösterilir. Bu gerçekten böyle midir? Kızıl sırtlı örümcekkuşunun (başlangıç ve bitiş zamanları iyi bilinmeyen) uzun bir göç aralığı vardır. Ağustos 2005 itibariyle Kuşbank veritabanında bulunan 313 kayıttan 128'inin (%41'inin) kayıtla ilişkilendirilmiş bir üreme kodu bulunmakta, sadece yedisinde (%2) kesin üremeye dair itiraz edilemez kanıt içermektedir. Geri kalan 121 kayıttan, 35 tanesi dışında hepsi kolayca göç eden bireylere ait olabilir. Birkaç dakikalık inceleme bir olası üreme kaydını "muhtemel" hatta "kesin" üreme kaydına dönüştürebilir.

Uzun süreli tutarlı veri toplamak

1986'dan bu güne IWRB/Wetlands International tarafından organize edilen Kış Ortası Su Kuşu Sayımları. Ancak, bu program için on yıldan fazladır veri toplanmasına rağmen sayımların yapılma şekli bu süre boyunca belirgin değişkenlik göstermiştir: ziyaret edilen yerlerin sayısı, her alanın kapsanma şekli ve sayıma katılanların sayısı ve deneyimi değişiklik göstermektedir. Bu nedenle, kışlayan kuş sayılarındaki değişimi belirlemeye yönelik herhangi bir çalışma veri toplama değişkenlerinin etkisini de dikkate almak durumundadır. Bir tür gerçekten artıyor ya da azalıyor mu, yoksa sayılan alan sayısı mı artmış ya da azalmıştır, ya da söz konusu türün tanımlanması mı zordur, ya da alanlar belli bir yılda daha detaylı ya da daha üstün körü mü sayılmıştır? Üstelik kontrol edilemeyen değişkenler mutlaka var olmaya devam edeceklerdir: kuşların avcılara bağlı hareketliliği ya da Türkiye/Doğu Avrupa-Rusya-Orta Asya'daki hava durumu. 2012'de Ulusal KOSKS Kurulu çalışmaya başlamış, sayımlarda daha bütünleyici ve kapsamlı bir koordinasyon başlamış, sayılacak alanların kapsamları, isimleri ve önem dereceleri standartlaştırılmış, her alında kullanılacak sayım istasyonları sabitlenmiş ve tüm bu metotlar ve protokoller formlar ve haritalarla herkesin erişimine sunulmuştur. Ayrıca gözlem kayıtlarının sistematik bir şekilde Kuşbank'a girilmesi, hem veriye erişimi, hem de raporun hatasız bir şekilde hazırlanmasını kolaylaştırmıştır.

Bir alanı kullanan kuşların sayısının yıldan yıla ve mevsimden mevsime değişmesi doğaldır. ÖKA olmayı hak eden bir alan kötü bir yılda tümüyle gözden kaçabilir ve tam aksine belki de komşu alanlarda uygunsuz su seviyeleri nedeniyle olağan üstü iyi bir yıl geçiren bir başka alan, aslında sadece sulakalanlar ağındaki işlevi ile önemliyken, koruma için en önemli yerlerden biri olarak işaretlenebilir.

\(3\) Gözden kaçan türler

Bazı kuşlar diğerlerine göre daha çok göze batarlar ve bazılarını görmenize bile gerek yoktur. Bunun tam aksine, görülmesi, ulaşılması ve tanımlanması zor olanlar vardır. Gececil kuşlar özel teknikler kullanılmadığı sürece her zaman olduklarından daha az kayda geçerler, saklanan ve sakınan türler bolca bulundukları halde hiç fark edilmeyebilirler. Paçalı baykuş da ülkede aslında oldukça yaygın olabilecek bir tür için çarpıcı bir olası örnek oluşturur, 25 yıl öncesine kadar hiç kaydedilmemişti.

Koloni halinde üreyen türler, uygun yaşam ortamı olduğunda bile düzensiz dağılım gösterirler ve akbabalar gibi bazıları uzak ve erişilmez yerlerde bulunabilirler. Bir koloni bir kez keşfedilince popülasyonu izlemek nispeten kolaydır ama yeni bir koloni daha bulmak hiç de kolay olmayabilir. İspir'deki kızıl akbaba kolonisini ele alalım, koloniyi yola komşu kayalıklarda olduğu için biliyoruz, uzaktaki tepelerde ve komşu vadilerde ne olduğundan ise haberimiz yok.

Alpin türler hemen her zaman parçalı dağılım gösterirler, düşük yoğunlukta bulunurlar ve bir yerde sadece kısa bir süre kalabilirler. Bunların bir sonucu olarak, yükseklerde yaşayan kuş türlerinin dağılımını yeterince bilemiyoruz.

Kuş türlerini sesleri ile tanınmaları zordur. Son yıllarda oldukça gelişme sağlanmış olsa da, Türk kuş gözlemcilerinin bu konuda nispeten az deneyimlidir. Diğer taraftan da pek çok türün bölgesel alttür ve ırklarının ötüş ve şarkıları hakkında bilgi yetersizliğimiz vardır. Türk kızılkuyruklarının bir ötüşü, en deneyimli Avrupalı kulaklarına bile şakrakkuşu gibi gelir. Bazı alanlarda boz kirazkuşlarının şarkısı tamı tamına kirazkuşuna benzer ve kirazkuşunun yaygın olduğu bölgelerde tamamen gözden kaçabilir.

POPÜLASYONLAR VE YAŞAM ORTAMLARI

Batı Avrupa'da her tür için güvenilir ve bazen de çok kesin popülasyon rakamları bulunur. Koruma eylemleri gerçekleştirilebilir çok daha uzak erimli koruma yararları sağlayabilecek Avrupa Birliği politikalarının oluşturulmasına katkı sağlarlar.

Türkiye'de güvenilir niteleyici bilgi ya hiç yok ya da eskidir. Kuş gözlemcisi sayısına göre ülkenin çok büyük olmasının yanı sıra, yerleşik kuş gözlemcileri bir de, Türkiye'yi yurtdışından ziyaret eden çok sayıda kuş gözlemcisinin aksine, sistematik değerlendirme çalışmalarına katılabilmek için yeterli deneyime, zamana, paraya, seyahat serbestisine ve eğitime sahip çok az kişinin olmasından da sıkıntıdadırlar. Üstelik ülkede kuşlara dönük akademik ilgi oldukça yeni olup henüz sadece bir kaç tane yüksek lisans ve doktora tezi tamamlanmıştır.

Yüksek profilli, yüksek koruma değeri olan toy, leylek, kara akbaba ve huş tavuğu gibi türler için birçok tek tür araştırmaları yapılmış ya da halen yapılmaktadır; bu çalışmalarda sayıları belirlemek için kuş gözlemcilerinden ve bölge halkından bilgi isteyen duyurulardan (leylek), radyo vericileri ile izlemeye (kara akbaba) ve dağılım ve popülasyon büyüklüğünün bilgisayar destekli modellenmesine (huş tavuğu) kadar çeşitli yöntemler kullanılmaktadır. Ne yazık ki, türlerin büyük çoğunluğu için en ilkel yöntem olan "en iyi tahmin" bilgisinden başka bilgi mevcut değildir. Şu an için, Birecik'teki yarı evcil kelaynak kolonisi haricinde, Türkiye'de muhtemelen hiç bir kuş türü için güvenilir nüfus tahmini bulunmamaktadır.

Sulakalanlar, barındırdığı olağanüstü kuş hayatı ve gözleme kolaylığı ile kuş gözlemcilerini doğal olarak cezbeder. Kuş kayıtlarının çoğu hala sulakalanlardan gelmeye devam etmektedir. Zaman içinde, bu sulakalan taraflılığı, Devlet Su İşleri işini şevkle ve etkin şekilde yaparak 1930'ların master planlarına uygun olarak sulakalanları kurutup barajlar inşa ettikçe bunaltıcı bir kayıp türler ve alanlar listesine dönüşmüştür.

GÖÇ ÇALIŞMALARI VE İZLEME

Gündüz yırtıcılarının ve diğer süzülen kuşların görülebilir göçü bu konuda en çok araştırılan konu olmuştur. Türkiye'nin göç eden kuşlar için önemi çok uzun zamandır bilinmesine rağmen, göçün sürdürülebilir, eşgüdümlü izlemi konusunda pek bir şey yapılmamıştır. 1960'lar ve 70'lerde İstanbul Boğazı, Kuzey-Batı Türkiye ve İskenderun Körfezinde gündüz yırtıcılarının ve süzülen kuşların gözlenmesi (Porter & Willis 1968, Beaman & Porter 1977, Beaman 1977, Sutherland & Brooks 1981) batılı kuş gözlemcilerinin Türkiye'deki görülmeye değer göçün farkına varmalarını sağladı ve bir ziyaret furyasına neden oldu.

Görülebilir göçün sayılması kendini işe adamış az sayıda sayıcının uzun süreli bir konsantrasyonla yaptığı ve büyük disiplin gerektiren bir iştir ve bu nedenle dünyada çok az sayıda düzenli ve uzun süreli gündüz yırtıcısı göçü çalışması yapılabilmektedir; ayrıca, elde edilen verinin gözle görülür koruma değerinin ortaya konması zor olduğundan yırtıcı sayımları için mali kaynak bulmak da zordur. Ancak, süzülen kuş göçü son derece görmeye değer bir olaydır ve halkın doğal çevresi ve korunma gereksinimi konusunda farkındalığı ve iradesini arttırmak için çok güçlü bir araçtır ve önemi kesinlikle küçümsenmemelidir.

Halkalama Çalışmaları

Genellikle ötücü kuşların ve yağmurcunların halkalanmasını gerektiren bu tür çalışmalar, WIWO'nun Çukurova (Kivit vd. 1992) ve Kızılırmak (1992 -- Hustings & van Dijk 1994) Delta'larındaki iki çalışması ile başlamıştır. 2002'de ulusal halkalama programının hayata geçirilmesi, eğitimli halkalamacılar yetiştirmiş ve Ankara, Manyas, Manavgat, Kars, Diyarbakır ve Kızılırmak Deltası'nda ilkbahar ve sonbaharda halkalama yapılmasını içeren koordineli bir program oluşturmuştur; bunlardan en eski ve süreklisi Kızılırmak Delta'sındaki Cernek Halkalama İstasyonu olmuştur(Barış 2005). Koruma açısından bu tür çalışmaların uzun vadeli yararı konaklama alanlarını kullanan kuş sayılarını, değişim oranlarını ve popülasyonlardaki değişimleri saptamalarındadır, böylece her alanın kuşlar için gerçek önemi belirlenebilir. Sürekli ve standart çalışma yapan halkalama istasyonları uzun vadede Türk ornitolojisine, veri sağlamaktan çok daha fazla katkı sağlarlar.

Kuşbank

Türkiye için yukarıdaki tüm bilgiler toplandığında, verileri, isteklilerin özellikle de bilgiyi kuşları korumak için kullanmak isteyenlerin ulaşabileceği bir yerde ve formatta saklamak önemlidir. Kuruluşuna 2001'de başlanan ve 2004'de kullanıma açılan KuşBank ağ-temelli veri tabanı tam da bu amaç için geliştirilmiştir. Kuşbank kuş gözlemcileri tarafından yaygın kabul görmüş ve son derece başarılı olmuştur-Kasım 2005 sonuna dek veritabanına 350 gözlemevi tarafından, 400 türe ait 97 000 'den fazla kayıt girilmiştir. Ancak, gerçekten değerli olabilmesi için Kuşbank'taki verilerin kalitesi güvence altında olmalıdır, bu nedenle belli standartların karşılandığından emin olabilmek için bir Kayıt Komitesi oluşturulmuştur. Başlangıçta sadece Kuşbank'a girilmiş kayıtları değerlendiren komitenin zamanla ulusal nadir kuş türleri komitesinin oluşumunun temelini sağlayacağı ümit edilmektedir.

Bir Sonraki Adım: Türkiye Üreyen Kuş Atlası

Tüm bu gelişmelere rağmen orijinal metinde vurgulanan yöntemselliğe dayalı nitelikli çalışmalar ve güvenilir verilerle koruma önceliklerimizi belirleyebilmek hala önümüzde aşılması gereken en önemli sorun olarak durmaktadır. Kendi başına yöntemsel çalışmaları gerçekleştirebilecek kuş gözlemcisi sayısı belki yüz kişi sınırını zorlasa da, orijinal yazının tespitleri ve eleştirileri hala güncelliğini korumaktadır. Bu aşamada, kuş gözlemcilerinin emeklerinin korumaya katkıda bulunması için daha etkili stratejiler geliştirme gereksinimi vardır. Koruma liderlerinin öncelikli alan, tür ya da veri eksikliklerini sistematik olarak belirlemeleri, akademik kapasitesi her gün artan üniversitelerin de katkısı ile kuş gözlemcisi topluluğunun veri açıklarımızı giderme konusunda daha verimli olmasını sağlayacaktır. Kış Ortası Su Kuşu Sayımlarının analizinin yapılması, yaygın kuş gözlem programının ulusal ölçekte bilgi sağlayacak şekilde yaygınlaştırılması ve dinamik kuş atlası hala hayata geçirilmeyi beklemektedirler.

## Ornitoloji Tarihi

Çeviren ve Uyarlayan: Bahtiyar Kurt ve Kerem Ali Boyla

Türkiye'de ornitolojinin ilk dönemlerine ait ilk derleme Kumerloeve tarafından Türkiye Ornitoloji Derneği (OST --Ornithological Society of Turkey) için hazırlanmıştı. Yayında son beş yüzyıldaki çalışmaların bir özeti yer almaktaydı. Ardından Guy M. Kirwan, Richard F. Porter, Güneşin Aydemir, Bahtiyar Kurt ve Gernant Magnin

İlk Çalışmalar

1548 yılında Pierre Belon Suriye'den İstanbul'a Anadolu'yu geçti ve 1555 yılında izlenimlerini L'histoire de la nature des Oyseaux adlı kitapta topladı. Böylece Anadolu'nun kuşları hakkında bilgi içeren ilk yayın hayata geçmiş oldu. 1720 yılında Smryna (İzmir) bölgesinde Britanya Konsolosu olarak görev yapan W. Sherard bir yalıçapkını yakaladı ve tür Linne tarafından Alcedo smyrnensis (İzmir yalıçapkını) olarak adlandırıldı. Bu tür aynı zamanda Türkiye'den toplanan ilk örnek oldu. 1792 ve 1796 arasında G.A. Oliver tarafından gerçekleştirilen seyahatler İstanbul Boğazı'ndaki yelkovanları raporlayan ilk gözlemler oldu.

1800'ler

Hugh Strickland'ın 1835-6 yıllarına ait gözlemleri Smyrna (İzmir) bölgesi için 129 türü listelemekteydi. Başka bir İngiliz, Keith Abbott, 1835 -- 1837 yılları arasında Trebizond (Trabzon) ve Erzeroom (Erzurum) bölgelerinde kuş kayıtları toplamaktaydı. 1850'lerde Marchese Orazio Antinori kuş derilerini toplayıp ticaretini yapmaktaydı ve 1856 yılında bugün Dendrocopus syriacus (alaca ağaçkakan) olarak adlandırılan ağaçkakan türü o zaman Osmanlı İmparatorluğu altında yer alan Suriye adıyla tanımlamıştı. 1840 -- 60 yılları arasında L. Rigler isimli bir fizikçi Konstantinopolis (İstanbul) bölgesinden 164 kuş türü raporladı. 19. yüzyılın ikinci yarısında yapılan gözlemler genelde İstanbul bölgesinden gelmiş olmakla birlikte Anadolu'nun diğer bölgelerinde de keşifler yapılmaya başlanmıştı. A. Günther 1865 yılında Ibis dergisindeki bir makalesinde İstanbul'da yaşamakta olan Thomas Robson tarafından toplanan bilgilere dayanarak uzun kuyruklu baştankaranın yeni bir alt türünden bahsetmekteydi. Robson kendi adına hiçbir zaman bir makale yazmamakla birlikte ornitolojiye katkısı oldukça fazlaydı.

1880'de Comte Amede Alleon (ve asistanı Vian) dünyayı bölgedeki inanılmaz leylek ve yırtıcı göçü konusunda bilgilendirmeye başladı. Daha güneyde 1863 ve 1894 yılları arasında bir ornitolog ve deri - yumurta taciri olan Theodor Krüper İzmir bölgesi ve Yunanistan'da oldukça aktifti. Kendi adını taşıyan sıvacının yanı sıra maskeli örümcekkuşu, boz kuyrukkakan, taş bülbülü ve yaz atmacası gibi türler hakkında oldukça faydalı çalışmalar yaptı. Bu zamana kadar Güney ve İç Anadolu ornitolojik açıdan neredeyse hiç araştırılmamıştı. Bir başka İngiliz Charles Danford 1870'lerin sonlarında bu bölgelere yönelik araştırmalar gerçekleştirdi ve Fırat Nehri üzerinde bulunan Birecik'teki kelaynak kolonisini keşfetti. Dresser, Danford'un bulguları üzerine çalıştı ve başka önemli keşiflerin yanı sıra Toroslar'dan urkekliğin bir alttürünü tanımladı. Bu yüzyılı kapamadan önce son olarak başta Radde (1884) ve Vilkonskij (1897) olmak üzere Rus ornitologların özellikle Kuzeydoğu Anadolu'da kuş araştırmalarına başladığından da bahsetmek gerekir.

1900 -- 45

Bu yüzyıl İstanbul ve Kuzeybatı Anadolu'dan bildiren Braun (1901 -11) ile başlıyor. Aynı dönemde Kuzeydoğu ve Doğu Anadolu'da gözlemler yapan Woosnam ve Güney Anadolu bölgelerinden kayıtlar tutan Ramsay öne çıkan isimler. Ayrıca İskenderun ve Belen Geçidi bölgesindeki leylek göçlerini kaydeden Hubert Lynes'den de bahsetmek gerekir. Kuzeydoğu bölgesinde Nesterov, Bobrinkij ve Dombrovskij liderliğinde Rusların çalışmaları yüzyılın ilk 20 yılında ağırlık kazandı. Erzurum bölgesinde İngiliz ornitologların çalışmaları Weigold tarafından yürütülmeye devam etti ve birkaç yıl boyunca Birecik'teki kelaynak kolonisini ziyaret etti.

1920'de Türkiye'den bir biyolog, Ali Wahby, İstanbul'dan kayıt toplamaya başladı ve kendisi ülkedeki ilk kuş halkalayıcısı oldu (leylekler). 1930 ve 1934 yıllarında yayımlanan "Les oiseaux de la region de Stamboul et de ses environs" bir Türk tarafından hazırlanan ilk yayın oldu.

Aynı dönemde Otto Steinfatt ve Lutz Mauve Boğaziçi'nde kapsamlı göç izleme çalışmaları yaptılar. 1933 yılında meşhur Albay Richard Meinertzhagen Amik Gölü'nü ziyaret etti ve yılanboyun kolonisi hakkındaki nadir gözlemlerden birkaçını belgeledi. Hugo Rossner ve Gabriele Neuhauser (Kuzey Anadolu), C.G. Bird ve E.K. Balls (Doğu Toroslar ve Güneydoğu Anadolu Dağları), Miklos Vasvari ve Imre Patkai (Karacabey ve Uluabat Gölü) bu dönemin araştırmalarına imza atan diğer araştırmacılar oldular. N. J. P. Wadley İkinci Dünya Savaşı süresinde Türkiye'de kuşları izleyen nadir araştırmacılardan biri olarak yaklaşık 205 tür kaydetti ve kayıtları "Notes on the birds of Central Anatolia" başlığıyla Ibis'te yer aldı. 1951 yılında Phil Hollom Türkiye'ye bir ziyaret gerçekleştirdi ve kara iskete ve ada martısı gibi önemli türleri gözlemledi.

1950'ler ve 1960'lar'da Alman Ekolü

1930'lar Alman Hans Kumerloeve'nin Gunther Niethammer ile birlikte ülkeye ilk ziyaretlerine tanıklık etti. Kumerloeve'nin günümüzde hala referans olarak gösterilen önemli eseri Zur Kenntnis der Avifauna Kleinasiens'e dayanmaktaydı. 1953 ve sonrasında Hans Kumerloeve Anadolu'daki detaylı kuş araştırmalarına başladı ve 1969 yılına kadar neredeyse tüm ülkeyi baştan aşağıya dolaştı. Neredeyse her ay bir makale yayımlamaktaydı. 1986 yılında o güne kadar kuşlar ve memeliler konusunda yayınlanmış yayınların bir bibliografyasını oluşturdu. Dr. Hans Kumerloeve 20. yüzyıl Türkiye ornitolojisinin duayeni olarak kabul edilebilir.

Curt Kosswig, Türkiye'ye 1936'da gelerek İstanbul Üniversitesi Fen Fakültesi Zooloji Kürsüsünün başkanı olarak göreve başladı. Manyas Gölü'ndeki balıkçıl konusundaki araştırmaları sırasında buradaki kuş kolonileri konusunda çalışmalar gerçekleştirdi ve bunun sonucunda alan Kuş Cenneti statüsüyle 1958 yılında koruma altına alındı. Aynı zamanda asistanı olarak akademik yaşamına başlayan Saadet Ergene Curt Kosswig'in etkisi ile kuşlarla ilgili çalışmaya başlamış ve 1945 yılında doçentlik çalışması olan ilk resimli Türkçe kuş kitabı "Türkiye'nin Kuşları" 1945'de yayımlanmıştır.

Diğer Alman araştırmacılar arasında İç Anadolu'da çalışan Gottfried Vauk, Heinz Lehmann ve arkadaşları ve Klaus Warncke öne çıkanları oldu. Tepeli pelikan, boz kaz, kuğu, uludoğan, flamingo ve alamecek türlerine ait bilgileri topladılar. 1968 yılında Willy Bauer ve Günther Müller Meriç Deltası'ndaki çalışmaları kapsamında kurutulma tehdidi altında bulunan alan için bir yönetim planı hazırladılar. 1967 yılında Uluslararası Kış Ortası Su Kuşu Sayımları ilk kez Türkiye'yi de kapsadı ve sayımları J. Szijj ve Hayo Hoekstra gerçekleştirdi. Sonraki yıllarda sayımlar Hollandalı Lieuwe Dijksen ve Fred Koning tarafından gerçekleştirildi.

Richard Porter ve OSME

Richard Porter ve arkadaşları, 1966'da İstanbul'a gelerek Boğaz üzerindeki ilk kapsamlı modern sayımı gerçekleştirdiler. Alleon ve Vian'ın 1880 yılında yaptığı Boğaziçi'nin süzülen kuş göçü yazıları Porter'ı etkileyen diğer bir kaynak oldu. Bunun yanında 1950'ler ve 1960'larda Nisbet ve Smout, Ballance ve Lee'de yırtıcı göç gözlemlerini Ibis Dergisinde yayımlamışlardı. Bu dönemde C.T. Nisbet, T.C. Smout, D.K. Ballance, S.L.B. Lee ve Hartmut Heckenroth İstanbul Boğazı'nda göç izleme çalışmalarına yenilerini eklediler.

Richard Porter'in 1966 yılında Türkiye'ye ilk ziyaretini yaptığında Türkiye'deki kuş gözlemcilerin sayısı bir elin parmaklarını geçmiyordu: Milli Parklar bölümünden Tansu Gürpınar ve Türkiye'nin ilk kuş cenneti Manyas Gölü'nün bekçisi Ali Kızılay ilk gözlemcilerdendi. Gürpınar, Milli Parklar Müdürü Dr. Zeki Bayar'ın da desteğiyle Türkiye'nin ornitoloji ve koruma hareketini yaygınlaştırma çalışmalarını gerçekleştirdi.

1968 yılında aralarında Tansu Gürpınar'ın da bulunduğu çoğunluğu yabancı bir grup Türkiye Ornitoloji Derneği'ni (OST -- Ornithological Society of Turkey) kurunca çalışmalar farklı bir kimliğe büründü. Uluslararası Doğayı Koruma Birliği (Bugünkü Dünya Sulakalanlar Kurumu -- Wetlands International) ve Uluslararası Kuşları Koruma Konseyi (Bugünkü Dünya Kuşları Koruma Kurumu -- BirdLife International) desteğiyle Ankara, Bursa ve İstanbul'da gerçekleştirilen konferanslar Türkiye yaban hayatının korunması yönünde önemli kararlar alınmasına öncülük etti ve Ramsar Konferansı'nın ilk adımları da bu toplantılarda atıldı. OST'un kurulması kararı da yine bu konferanslarda karara bağlandı. 1968'den 1978 yılına kadarki sürede OST Türkiye için 4 ayrı kuş raporu, 15 adet de bülten yayımladı. Türkiye'nin ilk kuş listesi 1971 yılında OST tarafından basıldı. Bu yayında Türkiye için 394 türü sıralanmıştı ve bunlardan 251 tanesinin ülkede düzenli ürediği söylenmekteydi. 1976 yılında Doğu Karadeniz bölgesinde göç izleme çalışmaları sırasında OST'nin tüm Ortadoğu'yu kapsaması fikri ilk kez ortaya atıldı. 1978 yılında Ortadoğu Ornitoloji Derneği (OSME -- Ornithological Society of the Middle East) dünyanın ilk bölgesel kuş kulübü olarak kuruldu.

OST döneminde yapılan çalışmalara katkı verenlerin arasında OST'nin ilk başkanı William Wilkinson'dan bahsetmek gerekli. Her ne kadar literatürde hak ettiği kadar yer almasa o dönemde gerçekleştirilen birçok ornitolojik çalışmanın arkasında bulunmaktaydı. Bunun dışında F. Hüe ve R.D. Etchecopar tarafından hazırlanan Les Oiseaux du Proche et du Moyen Orient yayını da hatırlamak gerekli. Bu yayın uzun yıllar Ortadoğu için standart bir başvuru kaynağı görevi görmüştür. OST'nin kimlik değiştirmesini takiben OSME'nin dergisi Sandgrouse'da beş yılda bir Türkiye Kuş Raporları yayınlanmaya devam etti.

1980'lerde Türkiye kuş gözlem tarihi için önemli bir Alman isim devreye girdi. Kasparek Türkiye avifaunası üzerine birçok eser yayımladı. Bunların arasında özellikle iki kilit çalışma yer alıyordu; 1961 yılından bu yana ilk kez ele alınan "Die Vögel der Türkei"; ve Kasparek'in eşi ve Asaf Ertan ile birlikte hazırlanan "Türkiye'nin Önemli Kuş Alanları" envanteri.

Doğal Hayatı Koruma Derneği

1960'ların sonunda ve 1970'lerin ilk yıllarında tüm bu sürece paralel bir yaklaşım da Salih ve Belkıs Acar çifti tarafından hayata geçirilmekteydi. Sonsuz enerjileri ve vizyonları Türkiye'de gönüllü doğa koruma hareketinin esin kaynağını oluşturmuş ve bu çabaların bir ürünü olarak 1975 yılında Doğal Hayatı Koruma Derneği (DHKD) kurulmuştu. Bu dönem OST'nin son zamanları olmakla beraber Türkiye ornitolojisinin de başlangıcına şahitlik edecekti. 1986 yılında Uluslararası Kuş Koruma Konseyi (bugünkü Dünya Kuşları Koruma Birliği, BirdLife International) Türkiye'nin kuşlar açısından önemini benimseyerek DHKD'nin desteklenmesi için bir Hollandalıyı görevlendirdi: Gernant Magnin. 1988 yılında DHKD'de çalışmaya başladı, Murat Yarar ile birlikte kuş bölümü bünyesinde sayılı yerli kuş araştırmacılarını topladı. Magnin ve Yarar 1992 ve 1997 yılları arasında yaklaşık yarım milyon kilometre yol kat ederek birçok kuş verisi topladılar ve bu çalışmanın sonucunda Türkiye'nin Önemli Kuş Alanları (ÖKA) kitabı 1997 yılında yayımlandı.

DHKD İstanbul'daki modern ofisi ve çalışanlarıyla artık güçlü bir kurum olmaya başlamıştı. Sayısı yabancı kuruluşla beraber çalıştılar, bunların arasında: Tour du Valat (Fransa), Dünya Sulakalanlar Kurumu (Wetlands International), Uluslararası Kıyıkuşu ve Sukuşu Araştırma Vakfı (WIWO, Hollanda) ve OSME önde gelenler oldu. Burada özellikle WIWO'nun katkısından bahsetmek gerekir ki yaptıkları birçok çalışma ve ürettikleri raporlarla özellikle ÖKA'ların güncellenmesinde aktif rol aldılar. DHKD Kuş Bölümü, 1995 yılında ODTÜ Biyoloji Bölümü'nde çeşitli uzmanların katıldığı bir toplantıya önayak olmuş, uzmanlar tarafından tür isimleri konusunda uzlaşma sağlanmış, bu liste 1996 yılında Doğal Hayatı Koruma Derneği tarafından Türkçe Kus İsimleri Listesi ismiyle yayımlanmıştır.

Kuş Gözlem Toplulukları

90'lı yıllar Türkiye'nin ilk kuş gözlem topluluklarının kurulumuna şahitlik etti. İlk topluluk 1991 yılında Ankara Kuş Gözlem Topluluğu, ardından Hacettepe Üniversitesi Kuş Gözlem Topluluğu (Beykuş) hayata geçti. 1995 yılında kurulan ODTÜ Kuş Gözlem Topluluğu zamanının en aktif ve uzun ömürlü topluluğu olarak tarihe geçti. 2000 yılında DHKD tarafından başlatılan ÖKA İzleme Programı kapsamında birçok kuş gözlem topluluğu kuruldu. Bahtiyar Kurt liderliğinde yürütülen çalışmalar kapsamında DHKD kuş gözlemcilere kitaplar, dürbünler, teleskoplar ve diğer hizmetleri sağladı ve kuş gözlemciliği bu dönemde sistematik olarak büyüdü Bu büyümenin önündeki en büyük kısıtlayıcı olan Türkçe kuş rehberi eksikliği de 2002 yılında Heinzel, Fitter ve Parslow tarafından hazırlanan Collins Kuş Rehberi'nin Kerem Ali Boyla tarafından Türkçe'ye çevrilmesi ve DHKD tarafından basılmasıyla ortadan kalkmış oldu. 2002 yılında DHKD'nin küllerinden doğan Doğa Derneği bu bayrağı devir alarak çalışmalara devam etti, Türkiye Kuş Gözlem Ağı'nı oluşturmak için eğitim çalışmaları, konferansalar düzenlendi ve bültenler çıkarıldı. Bu dönemde Kuşçu Bülteni etkin iletişim aracı oldu, 2004 yılından itibaren adı Kuşçu Postası olarak değişti. Buna paralel 1998 yılında kuş gözlemciler ve korumacılar Kuş Araştırmaları Derneği tarafından kuruldu ve onlar fa İbibik Dergisi beş sayı boyunca yayımlandı.

Türkiye'deki kuş araştırmacılarının artmasıyla artık bazı kapsamlı çalışmalar mümkün hale gelmişti. DHKD 1998 yılında Konya Havzasının kuşlarını detaylı şekilde ortaya koyacak bir araştırmayı hayata geçirdi. Bunu takiben iki İngiliz kuş gözlemci, Geoff ve Hilary Welch, liderliğinde Akdeniz ve Güneydoğu Anadolu'da da kuş araştırmaları gerçekleştirildi. Çift 15 yılı geçen çabalarıyla Türkiye'de hem birçok araştırmaya katkı verdi hem de birçok yerli gözlemcinin kapasitesinin gelişimini destekledi.

Ancak kuş gözlem toplulukları doğa korumada hayal edilen katkıları sağlayamadılar. Kuş gözlemcilerinin çoğunluğu kuşlara ilgileri yeni başlamış olan üniversite öğrencileriydi ve ilkbaharda gözleme ayırabilecekleri serbest zaman sınavlar nedeniyle büyük ölçüde kısıtlıydı. Aynı zamanda bu grubun kuşlara ilgisi genellikle eğitimlerinin tamamlanması ve yaşamlarını kazanmak zorunda kalmalarıyla birlikte sona ermekteydi. Çok azının maddi imkânları yeterliydi, pek azı araba kullanabilmekteydi, neredeyse hiç biri saha çalışması için gerekli dört çeker arazi araçlarına sahip edildi. Ve kuş gözlemcilerinin çoğunluğu İstanbul, Ankara, İzmir, Kayseri, Samsun ve Adana gibi birkaç kentte yaşamaktadırlar.

Kuşbank

Kuşbank, internet temelli bir kuş gözlem veritabanı olup, Uygar Özesmi tarafından ortaya atılmış ve geliştirilmiş ardından Doğa Derneği ile Dünya Kuşları Koruma Birliği (BirdLife International) ortaklığıyla hayata geçirilen Türkiye'nin ulusal kuş veritabanı olarak çok başarılı bir proje oldu. 2014 sonu itibarı ile veri tabanında yaklaşık 550 gözlemci tarafından girilmiş yaklaşık 440 türe ait 500.000'den fazla kayıt bulunmaktadır. Kuşbank veritabanının artık ulusal ölçekte veri analizine izin verecek düzeyde çok kayda sahip olması gelmektedir. Başlangıçta sadece Kuşbank düzeyinde kayıt incelemesi yapan kuş kayıt komitesi artık yazılı başvuruları ve fotoğrafik kanıtları da değerlendirmektedir, yine de henüz gerçek anlamda bir "nadir türler komitesinin" oluştuğu söylenemez.

Kuş Fotoğrafçılığı

Bir diğer önemli gelişme ise, geçen zaman içinde Türkiye'de önemli bir doğa fotoğrafçısı topluluğunun gelişmiş olmasıdır. Özellikle kuş fotoğrafları çekmeye tutkun gönüllüler, pek çoğu internet sitelerinde yayınlanan, yer ve zaman bilgisine sahip çok sayıda kuş fotoğrafı ile benzersiz bir veri kaynağının oluşmasını sağladıkları gibi, nadir ya da sadece belli yerlerde bulunan türleri görüntüleme tutkusu, ulusal ölçekte kuş turizmi ve rehberliğini de destekleyerek kuş verilerinin kapsam ve niteliğinin artmasını sağlamıştır. Bu sayede ak kaşlı çinte, mahmuzlu çinte, uzun kuyruklu korsan martı vb. pek çok nadir tür kayıt altına alınmış, balık baykuşu ve paçalı baykuş gibi başka bazılarının da üredikleri kanıtlanabilmiştir.

Kuş Gözlem Toplulukları çalışıyor\...

Aslında özellikle Türkçe yayınlar, internet grupları ve kuş gözlem toplulukları ile kuş gözlemciliği gelişimine kendiliğinden devam etti. 2007 sonrasında yerel kuş grupları giderek öğrenci grupları olmaktan çıkarak kentlerde yerleşik uzun soluklu topluluklar haline gelmişler ve bulundukları bölge ile ilgili daha nitelikli çalışmalara yönelmişlerdir. Bunlara arasında İstanbul kuş gözlem topluluğunun yırtıcı kuş sayımları ve yıllık gözlem kayıtlarını yayınlamaları, Bursa kuş gözlemcilerinin leylek sayımları sayılabilir.

Halkalama

Bazı istasyonlar zaman içinde düzenli çalışır olmaktan çıksa da halkalama çalışmaları, en azından Kızılırmak Deltası'nda, Kars'ta ve Antalya'da düzenli olarak devam etmektedir. Kuş gribine su kuşlarının katkısının uluslararası araştırıldığı projelerde su kuşları halkalanmış, örneklenmiş ve bazıları uydu vericileri ile takip edilmişlerdir. Yine 2003-2009 yılları arasında İzmir Tuzla'da yapılan beş adet flamingo halkalama çalışması Akdeniz'deki flamingo popülasyonları, dinamikleri ve korunmaları için önemli veri sağlamıştır (Balkız vd. 2009)

## Teşekkürler

Guy Kirwan, The Birds of Turkey kitabının baş yazarı olarak projeye başından beri önemli destek verdi. Cavit Bilen, maddi katkı sağlayarak projenin gerçekleşmesine yardımcı oldu. Kitabın temelini oluşturan metinleri çeviren isimler arasında, başta Özge Keşaplı Can ve Özgür Keşaplı Didrickson olmak üzere, Önder Cırık, Ömer Döndüren, Utku Perktaş ve Kuzey Cem Kulaçoğlu yer alıyor. Türkiye Ornitolojisinin Tarihini hazırlayan isim Bahtiyar Kurt olurken, Sancar Barış Veri Boşlukları kısmını düzenleyerek önemli bir katkı sağladı.

Revizyonları gerçekleştiren isimler arasında Dilek Şahin, Orhan Gül, Ortaç Onmuş, Özge Balkız ve Özgün Sözüer bulunuyor. Projeyi başından beri destekleyen isimler arasında Cumhur Öztürk, Engin Gem, Emrah Çoraman, Budak, Kemal Nuraydın ve WWF-Türkiye yer alırken, kitaptaki grafikleri revize eden Emrah Çoraman, Kiraz Erciyas Yavuz ve Ömral Ünsal Özkoç, kitabın görsel estetiğine önemli katkılarda bulundular.

Adil Güner, bazı bitki türlerinin Türkçe isimleri konusunda yardım sağlarken, Nadir Tür Komitesi olarak çalışan Ali Atahan, Nizamettin Yavuz, Mustafa Erturhan, Kiraz Erciyas Yavuz, Metehan Özen ve Ömral Ünsal Özkoç, nadir türlerin kayıtlarını eksiksiz bir şekilde derleyerek projeye önemli bir destek sundular.

Kitabın çıkması dışında yayıncının ötesinde ilgi ve destek veren Hülya Tokmak ve Ahmet Boratav'a teşekkürler. Haritaların tasarımında destek olan Budak, Kemal Nuraydın, Mustafa Dağıstanlı, Oya Ayman ve Nesibe Bat, deneyimleri ve bilgileri ile projenin olgunlaşmasına katkıda bulundular.

Son olarak, fotoğrafçılar ve gözlemcilerin kayıtları ile Kuşbank'a önemli veri sağlayan tüm katılımcılara teşekkür ediyoruz. Unutulmaz gözlemcileri rahmetle anıyoruz.
